### ISSUE TITLE
usher + chronumental + taxonium

### ISSUE THREAD

**Issue by ktmeaton** [theosanderson/taxonium#103]
Hi Theo,

I have custom UShER trees that I've run through chronumental, and am hoping to integrate these outputs into a taxonium protobuf. I think the general logic for this integration is in `usher_processing.py`? Is editing that script a good place for me to start, or is there an easier way?

Thanks!

**Comment by theosanderson** [comment]
Hi Katherine,

I'm excited that you are doing this, and thanks for raising the issue. Yes I am afraid the current best logic for this is the mess of `usher_processing.py`. In the case of the main Taxonium site this is directly run from https://github.com/theosanderson/taxonium/blob/master/.github/workflows/main.yml , if you want to see the context. 

I do hope in time to make this much more straightforward, and it's a great shame that this takes so much longer to run than the direct Usher export. Please let me know if you hit any issues or need anything explained. Thanks for using these tools!

**Comment by theosanderson** [comment]
[Taxoniumtools](https://github.com/theosanderson/taxonium/tree/master/taxoniumtools) is the new way to do this sort of thing in a single line

**Comment by ktmeaton** [comment]
I tried loading the test output from chronumental into <https://taxonium.org/> but don't have a "time" option for the tree type. Has that feature change/been removed? 

The example command in taxoniumtools worked perfectly though 👍

Chronumental JSONL: [tfci-taxonium.chronumental.jsonl.gz](https://github.com/theosanderson/taxonium/files/8594401/tfci-taxonium.chronumental.jsonl.gz)

![image](https://user-images.githubusercontent.com/14981272/166060948-373b3aaa-e1d4-448a-ac39-9a96930dfcf1.png)

**Comment by theosanderson** [comment]
Thanks @ktmeaton and sorry for the issue. This is a small config issue I need to fix, will let you know when that is in.

**Comment by theosanderson** [comment]
Should be working now - let me know if not, apologies again. 

(As an aside, Chronumental uses the earliest sample in the dataset as an anchor point atm, and if that sample is a metadata error things tend to go badly. That can be fixed by specifying an early node with `chronumental_reference_node` and hopefully we'll find a better solution soon)
