### ISSUE TITLE
React library

### ISSUE THREAD

**Issue by chaoran-chen** [theosanderson/taxonium#13]
Hi @theosanderson, I have been waiting so long for a fast tree viewer like this - thank you very much for the amazing work!

I was just wondering if you could imagine releasing it as a React component library. It would be great to see it embedded in probably a lot of websites.

**Comment by theosanderson** [comment]
Hi @chaoran-chen,

Thanks for this suggestion! I'd definitely be keen on this. One issue at the moment is that I pre-compute the node positions with a custom server-side script. So I might have to develop some client-side stuff for that, and at the moment it's unforunately slow. As you're probably aware https://www.phylocanvas.gl/ has also just been released so might be more useful to you out of the box at this moment. But I'll definitely try to make progress on this. We'd also need to strip out Tailwind, but that would be worth it for the re-use.

Cheers

**Comment by theosanderson** [comment]
@all-contributors Please add @chaoran-chen  for ideas

**Comment by theosanderson** [comment]
A couple of years later, completed in https://github.com/theosanderson/taxonium/pull/485
