### ISSUE TITLE
uncaught exception: out of memory on Firefox

### ISSUE THREAD

**Issue by InfrPopGen** [theosanderson/taxonium#236]
Please could you have a look at the following issue, which also occurred on a larger machine (more 128 GB RAM) and with Chromium too. Thank you.

Viewing tree from loaded .jsonl (e.g. public-2022-05-25.all.masked.taxonium.jsonl) fails with Firefox due to out of memory error.
Firefox 100.0.2 (64-bit) on Ubuntu 18.04.6, and 15GB system RAM.
The same machine was able to display the tree from the .pb using https://cov2tree-git-v1-theosanderson.vercel.app/. The error only occurred with the jsonl.

Firefox console log:
>>> 11:39:38.569 Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=G-TDTSH11X4S”. taxonium.org:1:1
11:40:21.617 new worker useLocalBackend.js:4:8
11:40:21.620 new scatter useLayers.js:79:12
11:40:21.653 Sending data to worker useLocalBackend.js:54:12
11:40:22.781 GETTING CONFIG useConfig.js:11:12
11:40:22.782 getConfig useLocalBackend.js:145:12
11:40:22.782 clearing cache useColorBy.js:51:12
11:40:22.783 updating parameters to query useGetDynamicData.js:41:14
11:40:22.783 updating bounds 
Object { min_x: NaN, max_x: NaN, min_y: NaN, max_y: NaN, zoom: -2, xType: "x_dist" }
useGetDynamicData.js:53:14
11:40:22.835 WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. polyfill-context.js:48:28
11:40:22.885 resize 
Object { width: 1550, height: 810 }
Deck.jsx:207:18
11:40:23.833 worker starting 814.8319ab73.chunk.js:1:7416
11:40:23.835 got message from worker 
Object { data: "Worker starting" }
useLocalBackend.js:21:10
11:40:25.752 Worker onmessage 814.8319ab73.chunk.js:1:12232
11:40:25.752
Object { type: "upload", data: {…}, proto: undefined }
 data 814.8319ab73.chunk.js:1:12273
11:40:26.930 Worker processJsonl 
Object { status: "loaded", filename: "public-2022-05-25.all.masked.taxonium.jsonl", data: ArrayBuffer, filetype: "jsonl" }
393.e88296f1.chunk.js:2:234131
11:41:06.452 WebGL warning: generateMipmap: Tex image TEXTURE_2D level 0 is incurring lazy initialization.
11:41:07.575 Worker onmessage 814.8319ab73.chunk.js:1:12232
11:41:07.575
Object { type: "config" }
 data 814.8319ab73.chunk.js:1:12273
11:41:07.575 Worker config 814.8319ab73.chunk.js:1:13273
11:41:07.576 Worker getConfig 814.8319ab73.chunk.js:1:9510
11:41:07.578 uncaught exception: out of memory

**Comment by theosanderson** [comment]
I've just rented a Paperspace VM running Ubuntu (admittedly moderately beefy - the smallest they had was 30 GB RAM) and was able to get things working fine in Chromium and slowly in Firefox. 

![image](https://user-images.githubusercontent.com/19732295/170536052-c57d6277-34df-4054-90cf-352e05461b90.png)

**Comment by theosanderson** [comment]
(Still keen to figure out your issue btw, not dismissing it!)

**Comment by theosanderson** [comment]
Thank you very much for raising this. I'm hopeful I've got to the bottom of it. I think it's because of lazy debugging console messages I had left in that print huge objects. Chrome handles these really well and so I hadn't noticed them having an effect but I think Firefox works differently. I've removed at least some and am interested to hear if you have a different experience. But I guess given that things weren't working in Chromium and were for me there may also be an orthogonal issue.

**Comment by theosanderson** [comment]
Thanks @InfrPopGen for these answers. 

I pushed quite a few changes yesterday which I hope might have made a difference to this issue. I wasn't 100% sure from your answer if the issue is persisting today or if you haven't been able to try?

**Comment by InfrPopGen** [comment]
Thank you for trying some changes, but the issue is unfortunately persistent. Today's console log with Firefox is:
>>> Navigated to https://taxonium.org/
10:26:07.639 Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=G-TDTSH11X4S”. taxonium.org:1:1
10:26:07.837 InstallTrigger is deprecated and will be removed in the future. FirefoxWarning.jsx:4:46
10:26:19.769 WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. polyfill-context.js:48:28
10:26:39.639 WebGL warning: generateMipmap: Tex image TEXTURE_2D level 0 is incurring lazy initialization.
10:26:58.051 uncaught exception: out of memory

**Comment by theosanderson** [comment]
Thanks @InfrPopGen. Please could you let me know if loading the URL https://taxonium.org/?protoUrl=https%3A%2F%2Fhgwdev.gi.ucsc.edu%2F~angie%2FUShER_SARS-CoV-2%2Fpublic-latest.all.masked.taxonium.jsonl.gz behaves any differently? (There is one reason to thing it might and this would narrow down what might be happening)

**Comment by theosanderson** [comment]
Oh wait! Hopefully that is the whole story. It looks like you are ungzipping the file before use. Please try supplying, whether locally or through the URL, the gzipped version, ending in "taxoxium.jsonl.gz". Otherwise we have to load the whole ungzipped version into memory and that doesn't work. I'm pretty hopeful this will be it.

**Comment by theosanderson** [comment]
I can confirm that I get an "Aw snap" with the non-gzipped version. I'll try to do something to make this clearer.

**Comment by theosanderson** [comment]
I've just pushed a change which should fix the original case with `.jsonl` (thanks, I'm sure this would catch out other people), but tbh you might as well use the `.jsonl.gz` and save yourself some space

**Comment by InfrPopGen** [comment]
Thank you! Yes, Chromium works fine with the .gz file, and Firefox too (although much much slower to load). Apologies for not trying the gzipped versions in the first place!

**Comment by theosanderson** [comment]
Awesome!
