### ISSUE TITLE
BUG: Horizontal zooming by pressing `ctrl` doesn't work on Brave on macOS (at least)

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#247]
I love that you now have horizontal zooming. I only just realized, this feature may have been around for a long time - so discoverability may still be improved I think (this is a major struggle for Auspice: how to make the functions intuitively discoverable).

Anyways, I got a bit annoyed of switching between horizontal/vertical zooming modes and I discovered that the tooltip text says: hold ctrl to zoom horizontal.

Unfortunately, that doesn't seem to work on my macOS Brave browser. Where have you tested this?

<img width="444" alt="image" src="https://user-images.githubusercontent.com/25161793/170861861-e479d71f-d526-41dd-9839-cb51f3494c7f.png">

**Comment by theosanderson** [comment]
Horizontal zoom hasn't been around so long. Maybe a month.

Something to flag is that the implementation of horizontal zoom is generally very challenging as axis-specific zoom isn't a working feature of the Deck.GL framework on which this is based.

I have previously tested this on Chrome on macOS, but have now tested on Firefox, *and Brave*. Working for me. By the way, the windows/apple key, or the alt key should work too. You could try those?

This was originally intended to be shift-scroll, but in macOS intercepts the shift-scroll and sends it as a "horizontal scroll" which I don't receive an event for, hence the use of ctrl. Perhaps in your case the OS is intercepting the ctrl-scroll.

**Comment by corneliusroemer** [comment]
Workaround: Firefox works well on macOS
