### ISSUE TITLE
Feature: Add explicit horizontal zooming buttons

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#248]
I love that you have horizontal zooming now. I think the UX could still be improved a lot though - switching modes is better than nothing but a bit inconvenient. Modulating via key press is good for power users but not very discoverable.

I think it would make sense to add two extra buttons to zoom in/out horizontally. That would help discoverability. And the UI is not overloaded with buttons in any way.

I would maybe order them as a 2 row block:
| V+ | V-  | 
|:---:|---|
| H+ | H-  |

**Comment by theosanderson** [comment]
Yes I've been thinking about this too. The only downside is the screen real estate on small screens but I do think it's probably worth it. Thanks for the feedback.

**Comment by theosanderson** [comment]
This is now implemented -- actually I was very confused about why I had posted https://github.com/theosanderson/taxonium/issues/257#issuecomment-1143621554 and I realise it was meant to go here..
