### ISSUE TITLE
Feature: Make zoom and pan work intuitively with a macOS trackpad

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#250]
Zooming and panning is already much improved with the addition of horizontal zooming.

I just tried using my Mac trackpad to explore the tree and while some motions worked surprisingly well, I think there's a lot of room for improvement to make it really nice and intuitive, a bit like Google Maps for trees. Showing maps and trees is actually similar in some ways.

So one could just get inspired by map UI patterns: double finger up/down: already works as zoom vertical, double finger left/right: could be used for horizontal zooming, maybe three fingers could be equal vertical and horizontal zooming etc (to keep aspect ratio.

**Comment by theosanderson** [comment]
This is a nice to have but would be pretty hard as it involves the depths of Deck.GL

**Comment by theosanderson** [comment]
Hah I actually have no idea why pinch-zoom is zooming horizontally on mac - that's not intended behaviour but I guess is useful once you figure it out!
