### ISSUE TITLE
BUG: Mutations at this node should be renamed `what to display (in general)`

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#257]
I love that you can configure whether to show aa and/or nuc mutations.

However, the naming of the boxes is a bit weird.

It's not just "Mutations at this node" but affects all mutations displayed.

Maybe you should move the box up and name it more generally: `mutations to show:`, then have `Mutations at this node:` below.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/25161793/171248998-8b9137c3-53ef-4ee2-ad1d-150998235e5c.png">

**Comment by corneliusroemer** [comment]
This setting seems to be duplicated (not necessarily a problem, but I prefer the way the setting is described here):
<img width="487" alt="image" src="https://user-images.githubusercontent.com/25161793/171252769-45ec365d-74c7-452b-9e89-d12e4fcb2823.png">

**Comment by theosanderson** [comment]
Originally it was just in the settings box but I realised many people would never discover it. Now it's also here I think it is more likely to be discovered. I've changed things a bit so it is not quite so intimately attached to mutations at this node, at least on larger screens.

**Comment by theosanderson** [comment]
Some sort of notification method telling you it is global when you toggle it may be good

**Comment by theosanderson** [comment]
note to self: use react hot toast

**Comment by theosanderson** [comment]
Thanks Angie (and Cornelius) two votes for the toast is useful, it will remain. The eyeball was meant to be a shorthand for "Visibility" but helpful to know that was not obvious to you, and on reflection as you say I use those sort of symbols nearby as buttons so it's confusing. I've removed the lemon :)
