### ISSUE TITLE
Treenome Browser

### ISSUE THREAD

**Issue by amkram** [theosanderson/taxonium#267]
Treenome browser is an extension to Taxonium that displays a "genome browser" for each genome in the tree. Currently being developed at the fork https://github.com/amkram/taxonium. Demo available at https://treenome.vercel.app/

This issue is for discussion of next steps for development and eventual integration.

**Comment by theosanderson** [comment]
And congrats again!! Looking great 🎉

**Comment by theosanderson** [comment]
Feel like a good spot for the turning on and off is maybe next to the  toggle between distance and time tree (when present, and same place when not)

**Comment by amkram** [comment]
I've addressed a number of these points and some others, which I'll document here:

1. I tentatively added a toggle-able sidebar to show/hide the search panel (with `sidebarOpen` in Taxonium.jsx). Also added a checkbox to toggle the browser under the distance/time tree toggle as you suggested. TODO: toggling the browser locks up for a bit before the box becomes "checked." I imagine this could be solved by splitting into a web worker.

2. Haven't looked too much into this yet, but it seems pretty doable. The genome browser toggle does stop the calculations from running in the background, however.

3. Made some changes so that all of the tree elements now appear on top of the browser. I think this is helpful for e.g. seeing the node labels when zoomed in. I can also see the argument for putting it completely behind the browser though, so open to suggestions on this.

4. Extended the background to the full height, with some minor cosmetic additions -- e.g. added background colors to match the ORFs.

5. Made some tweaks to the JBrowse color palette and CSS styles to integrate better into the app. Open to further suggestions on what else might look good.

6. This should work now.

7. Sorry, could you clarify this point? Is this to help extend the genome browser to accept non-SARS-CoV-2 genomes? 

8. I think the toggle-able sidebar leaves a decent amount of space now for the browser - also open to exploring this idea

-----------

Other misc. changes and future tasks:

- I added (many of) the annotation tracks from UCSC SARS-CoV-2 genome browser (accessible in the 3-bar settings menu in JBrowse) by querying the UCSC web api for BigBed and BigWig files. There are some non-file-based tracks that aren't included, but I think these tracks will cover most of what people might want to look at.

- The treenome now responds correctly to resizing the web browser window.

- The browser doesn't correctly sync upon first load until the tree is interacted with, at which point it "snaps" into place. Need to figure out a way to fix this.

- The incremental vertical zoom buttons (directly north-east of the screenshot button) don't work for some reason due to my changes. Need to track down why.

- There is some tearing in the genome background colors that occurs when zoomed in very far. 

----------

Thanks for all the suggestions. I think its getting closer! I will work on addressing the above items along with any other ideas/suggestions you might have.

**Comment by theosanderson** [comment]
Hey @amkram. This looks great. 

1. Looks great. The web worker would be great if possible.
2. Yes, I think this would solve 1 and 2 together. Feel free to reach out if you have problems with this.
3. My instinct is that it feels like a bug to have those overlapping. I'm not sure users will understand that it's an intentional decision and may think something has gone wrong.
4. Looks really nice
5. Looks really nice
6. Super cool
7. Yes exactly, but this was more of a note to myself than a task for you.
8. Definitely no longer an issue


Bug: with genome browser disabled tooltips at the right hand side get a bit messed up:
<img width="124" alt="image" src="https://user-images.githubusercontent.com/19732295/175049048-1f48bbc6-3d4b-4701-a885-cbecd6e010d2.png">

Sorry you're having the issues with zooming, that code has got (on my side) to be horribly tangled. (It's hard with this due to how DeckGL works). Let me know if you can't figure out what's wrong.

I agree it's very close to there.

**Comment by amkram** [comment]
Some new updates:

1.  Added a web worker for browser computations. Those computations should be disabled if the browser is disabled except for  caching the "zoomed out" version (to avoid a delay when enabling the browser).

3. Tree now goes behind the browser.  If we find people want to see labels overlaying the browser, we could maybe add as a toggle option in the future?

Tooltip bug: fixed

Zooming bug: fixed

Zoom to sample:
I modified the zoom to sample code to only zoom vertically while the browser is enabled (to avoid sending the tree behind the browser). 

Let me know if you notice any bugs or have any more suggestions to wrap things up!

**Comment by theosanderson** [comment]
Hey this is looking awesome, it's a lot smoother. Feels like it might be time to open a PR as we iron out final things.

I'm definitely fine with a toggle option that you propose under the cog modal.

Final things:
- thinking about non SARS-CoV-2 trees or trees without sequence data (hiding the option for example) - we now get quite a bit of usage for random. Let me do some thinking about how exactly we do this.
- Removing the demo text from the front page
- I would prefer to default to have the sidebar open

I've only looked at the code briefly but had a question re: 

https://github.com/amkram/taxonium/blob/634a388aa7cc21244bf40a840ec9ce23dcbb9d18/taxonium_web_client/src/hooks/useBrowserLayerData.js#L15

I do this a bit differently here: https://github.com/theosanderson/taxonium/blob/0d08f75f5e6c05f07df0749def5ef9e1c8db9ef0/taxonium_web_client/src/hooks/useLocalBackend.js#L5

I only import the worker once, upstream of the hook. My pattern feels simpler and fairly safe, wdyt?

**Comment by theosanderson** [comment]
I guess my version should be equivalent to your commented out ```const worker = useMemo(() => new Worker(new URL("../webworkers/browserWorker.js", import.meta.url)), []);``` so I presume it doesn't work in this case. Seems weird though.. will see if I can see anything.

**Comment by amkram** [comment]
At some point during my testing, making the web worker only once blew up memory and crashed the page, while killing it and remaking it did not, weirdly. But, I just reverted to your way and it now seems to work just fine! So I'm not sure what was going on there.

For non-SARS-CoV-2 trees, with just the tree (if there is mutation/sequence data), we should be able to display the variation part of the browser -- can maybe also provide an optional way to manually upload annotations / gene coordinates? Not sure where that would best fit in. Maybe a button under the browser toggle, or in the cog settings menu.

I'll start cleaning things up a bit and will open a PR whenever you say the word! Happy to zoom to go over things as we get closer to doing the merge

**Comment by theosanderson** [comment]
I guess people can't provide sequence data without using a JSONL file, and they almost can't make a JSONL file without a GenBank file (they can I think, but most won't), so we might as well capture the gb in the JSONL given that we can. Doesn't preclude also providing functionality for loading manually, and I don't think we need to block on this given that as you say it doesn't totally fail without it.

Do feel to open a PR whenever you like! Likewise happy to zoom!
