### ISSUE TITLE
Occasional error when clicking a node

### ISSUE THREAD

**Issue by amkram** [theosanderson/taxonium#331]
When e.g. zooming out quickly and clicking a node, sometimes the screen will go blank with
`TypeError: Cannot read properties of undefined (reading 'parent_id')` at `usePerNodeFunctions.js:9`

The line in question:

     while (cur_node.parent_id !== cur_node.node_id) {

I think its an issue where some part of data hasn't loaded yet and cur_node ends up undefined, so maybe a check that `cur_node` is defined would fix?

**Comment by theosanderson** [comment]
Thanks for raising!

**Comment by theosanderson** [comment]
I think this is mostly fixed -- if you manage to make it happen please let me know though. I maybe did once after this change but then couldn't repeat it..
