### ISSUE TITLE
Failing to load tree; not sure why (displays just 1 node)

### ISSUE THREAD

**Issue by niemasd** [theosanderson/taxonium#337]
I was hoping to use Taxonium to visualize a large tree I generated in a simulation experiment, which is in the following Newick file:

[merged_tree.time.txt](https://github.com/theosanderson/taxonium/files/9301104/merged_tree.time.txt)

Taxonium seems to load it, but then it displays just a single node:

<img width="951" alt="screen" src="https://user-images.githubusercontent.com/4195510/183937450-73c0ad22-f54e-4e47-af70-e8eeb0d7ffda.png">

Any help would be greatly appreciated!

**Comment by niemasd** [comment]
I think I found the issue! The Newick tree I used had the `[&R] ` prefix to denote that it's a rooted tree, which seems to have messed Taxonium up. When I removed the `[&R] ` prefix, Taxonium loaded the tree perfectly fine:

[merged_tree.time.txt](https://github.com/theosanderson/taxonium/files/9301256/merged_tree.time.txt)

<img width="954" alt="screen" src="https://user-images.githubusercontent.com/4195510/183938552-4f53eff3-6442-48cd-ad53-498086361b0f.png">

**Comment by theosanderson** [comment]
Thanks for reporting this and diagnosing the issue - should be fixed!

**Comment by niemasd** [comment]
Yes, works perfectly! Thanks for the quick fix!
