### ISSUE TITLE
Can't scroll down right panel to see node details when there are too many filters

### ISSUE THREAD

**Issue by AngieHinrichs** [theosanderson/taxonium#346]
It's really useful to me to be able to see the mutations on a node that I have clicked on, but when I have a lot of filters, the node details seem to be clipped at the bottom and I can't scroll down to see them ("Number of descendants" is at the bottom and I can't scroll down past that):
<img width="446" alt="image" src="https://user-images.githubusercontent.com/186983/185478492-e69cd067-1ab2-495c-951f-2bc5fe7aa5e6.png">

This is on taxonium.org with a local .jsonl.gz file.

Clipping also happens for leaf node details:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/186983/185478818-aa2edefa-3748-4faa-8a4e-b1fe0b0771c4.png">

**Comment by theosanderson** [comment]
Ah thanks @AngieHinrichs I think we must have broken this with the introduction of treenome, will fix

**Comment by theosanderson** [comment]
Here is a version where it was working, now finding what changed https://cov2tree-a2itff9bs-theosanderson.vercel.app/

**Comment by theosanderson** [comment]
This should be fixed! Thanks for flagging and let me know if anything persists.

**Comment by AngieHinrichs** [comment]
Yes, it's working now, thanks!
