### ISSUE TITLE
Q: What does "x" mean in pango lineage search?

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#370]
I'm wondering what the "x" checkbox means in Pango lineage search - could you add a tooltip that explains it?

<img width="435" alt="image" src="https://user-images.githubusercontent.com/25161793/189531875-bfced6ba-9c74-45fa-9de6-889aa966b180.png">

`m` seems to mean "multiple"

Also, is it possible to enable "wildcard" search, including all the children? Or is this the default mode, and `x` means "exact"?

**Comment by AngieHinrichs** [comment]
> Or is this the default mode, and x means "exact"?

Yep, this is the default.  So by default, "B.1.6" will also match "B.1.617" but you can check x to see only B.1.6.   I suspect you could type "A.5.5.1" to match "BA.5.5.1" though I haven't tried it (that middle of the word match definitely works with names).

**Comment by theosanderson** [comment]
Yeah this feature isn't particular polished and was implemented mostly for Angie (a bit more details on how this is handled for Cov2Tree in #213). We do already have tooltips so I'm going to close this, but I acknowledge there is general room for improvement in that feature.

![image](https://user-images.githubusercontent.com/19732295/189632606-509602e3-cb2e-44a1-a0b7-26a785dd403d.png)

**Comment by theosanderson** [comment]
I made these tooltips a bit more visible in #374. There is still definitely room for improvement!
