### ISSUE TITLE
ENH: Export branch mutation information when converting to Auspice JSON

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#371]
It's amazing that it's possible to browse the full Usher tree and use Auspice to analyse a subtree - this is an awesome combination of tools.

Unfortunately, it seems that you don't export mutations on the branches - this shouldn't be too hard, the information should be available.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/25161793/189532538-e777fd21-208a-43a2-8d15-cc03685c8577.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/25161793/189532534-30dd7c43-85a0-43bf-88de-2c3f659507a0.png">

**Comment by theosanderson** [comment]
Thanks for flagging this. I agree this would be good -- I think this is basically as far as we got in the time of the hackathon. I'll try to get to it soon (and thanks for trying to do it yourself!)

**Comment by theosanderson** [comment]
We seem to have code intended to do this: https://github.com/theosanderson/taxonium/blob/519a245665e7dff2d2bb96247c3933952a696421/taxonium_data_handling/exporting.js#L41 now investigating why it isn't doing its job

**Comment by theosanderson** [comment]
This was fixed in #375 - thank you for raising it!

**Comment by corneliusroemer** [comment]
Great this works now - love it!

I've found a use case now for which taxonium is the best tool in the world :) 

<img width="684" alt="image" src="https://user-images.githubusercontent.com/25161793/190872033-cf3bd89c-f408-4c87-a2d7-c96a42e96f65.png">

I may open some more issues to improve the information content of the auspice json to make the most of the data you have on Usher and taxonium.
