### ISSUE TITLE
DOC: Improve dev docs to make contributing easier

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#373]
I wanted to try to try improving `getNextstrainSubtreeJson` but couldn't figure out how to get started.

It would be amazing if there were better dev docs, helping with the setup.

I've managed to get the backend server setup and can test in the browser through localhost:8000 but don't know how to directly debug the `getNextstrainSubtreeJson` function - ideally stepping through it in VScode

**Comment by theosanderson** [comment]
Sorry I'm no expert on stepping through Node either, I tend to debug with logging atm. Agree setup could be better doced.

**Comment by theosanderson** [comment]
The other tip is `yarn link` for linking against the dependency module

**Comment by theosanderson** [comment]
This is a bit better: https://github.com/theosanderson/taxonium/blob/master/DEVELOPMENT.md I'm sure there is still room for improvement and welcome specific thoughts.
