### ISSUE TITLE
BUG: Occasional reloads of tree - potentially out of memory or killed by Safari?

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#384]
I'm using Taxonium on Safari - maybe I shouldn't if it isn't a target browser.

After a while of usage, 30min-1hr it crashes, this has happened repeatedly.

Safari warns me that the website uses lots of resources - not unexpected, but this could also be related to the crashing/reloading.

Or is this some sort of timeout? The site just reloads - it doesn't crash. But because reloading of tree takes about a minute this is not quite nice.

This is not a high priority error - but maybe it happens to other users. Maybe only on Safari.

**Comment by corneliusroemer** [comment]
Ah I see - it seems to happen whenever I use another tab - I should try another browser to see if this is browser specific.

**Comment by corneliusroemer** [comment]
Now it keeps reloading after it is just about to finish loading the 13m nodes. Hmm.

**Comment by corneliusroemer** [comment]
Now tried on Chrome, there it crashed much sooner, entered a query after tree loaded and boom - gone.

Error 5 - whatever that means

<img width="929" alt="image" src="https://user-images.githubusercontent.com/25161793/190876746-32ed8020-d230-4ec4-a346-61ddd7028381.png">

**Comment by corneliusroemer** [comment]
Chrome tells me: paused before potential out of memory crash in filtering. That could be it?

<img width="841" alt="image" src="https://user-images.githubusercontent.com/25161793/190876861-e9525f58-e753-47a9-963d-710ef0c0a958.png">

**Comment by corneliusroemer** [comment]
Could be on queries that return a lot of results - when I make a small query this doesn't happen.

**Comment by theosanderson** [comment]
So there's two largely separate issues here. From Googling I think it's expected that Safari will close (and then have to reload) tabs that use a lot of memory.

Then there's the general issue of memory consumption based crashes. I'll copy your stuff into https://github.com/theosanderson/taxonium/issues/372 where we can discuss that.

**Comment by corneliusroemer** [comment]
Safari doesn't close, at least in my case - it just tells you that the tab slows the computer down.

In fact, only Chrome ever crashed.

Safari was fine.

But both showed a weird reload behaviour, where without crash the existing tree would disappear and reload.

**Comment by theosanderson** [comment]
Behind the scenes, I'm pretty sure Safari is "closing" the tab (discarding the DOM, etc.) and then loading it when you need it again. The "solutions" discussed on[ this page](https://browserhow.com/how-to-disable-page-auto-reloading-on-safari-mac/) are pretty spammy, but I think the description of the phenomenon is real.
