### ISSUE TITLE
ENH: Reduce node loading log level to `verbose`

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#385]
I looked at the logs to see if anything precedes the crash/reload and was overwhelmed with a thousand logs at `info` level saying that another 10k lines were loaded.

I think this would be better at `verbose` level so it's not shown by default in Chrome dev tools.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/25161793/190876808-520e8512-6183-4d34-b7fa-bf6c25e8caea.png">

**Comment by theosanderson** [comment]
Thanks for raising. This logging has been somewhat useful for a couple of reasons: indicating that the backend is actually doing something when starting up (this uses the same codebase), and for debugging a user issue with loading large files. So I don't plan to remove for the moment. But if you enter "-Processed" in the Chrome filter bar, they will go.

**Comment by theosanderson** [comment]
(s/remove/change verbosity/g)
