### ISSUE TITLE
Backend Taxonium Read Config From URL

### ISSUE THREAD

**Issue by kvargha** [theosanderson/taxonium#399]
Can you please add a feature to download a config when setting the CONFIG_JSON environment variable to a URL?

**Comment by theosanderson** [comment]
Possibly at some point (and PRs welcome), but you should also be able to achieve this by appending `&configUrl=xxx` to the URL

**Comment by kvargha** [comment]
Thank you @theosanderson. I opened a PR here: https://github.com/theosanderson/taxonium/pull/400.

**Comment by theosanderson** [comment]
Thanks @kvargha !

**Comment by theosanderson** [comment]
@all-contributors please add @kvargha for code
