### ISSUE TITLE
Taxoniumtools does not say what port 5000 is used for, frontend, backend?

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#404]
Just got this error when trying it out for first time.

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/25161793/195102968-49fec77e-7908-42de-adf1-3a2d8c408c89.png">

Would be great to have slightly better information on what I can do to workaround this etc.

```
view_taxonium /Users/corneliusromer/Downloads/taxonium.jsonl
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taxonium/bin/view_taxonium", line 5, in <module>
    from taxoniumtools import view_taxonium
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taxonium/lib/python3.10/site-packages/taxoniumtools/view_taxonium.py", line 61, in <module>
    check_port_is_free(args.backend_port)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taxonium/lib/python3.10/site-packages/taxoniumtools/view_taxonium.py", line 21, in check_port_is_free
    raise Exception(f"Port {port} is already in use.")
Exception: Port 5000 is already in use.
```

**Comment by theosanderson** [comment]
I added at least a little additional help and changed the default ports to be more unique. That will only appear in next release. Thanks for reporting.

**Comment by theosanderson** [comment]
Ack - https://stackoverflow.com/questions/12151306/argparse-way-to-include-default-values-in-help sometime

**Comment by theosanderson** [comment]
Closing view_taxonium issues as this will be deprecated, and ultimately removed, in favour of an Electron app. Thanks for raising issues, which helped to clarify that the electron app was the best way forward.
