### ISSUE TITLE
taxoniumtools `Error: EISDIR: illegal operation on a directory`

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#406]
I tried out using taxoniumtools on my M1 mac and got the following error when opening `http://localhost:8000/?backend=http://localhost:3453`

```
Node.js v17.9.1
(node:1) ExperimentalWarning: Fetch is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
imported importing
importing is  {
processJsonl: [AsyncFunction: processJsonl],
generateConfig: [Function: generateConfig]
}
imported filtering
imported exporting
node:fs:728
handleErrorFromBinding(ctx);
^

Error: EISDIR: illegal operation on a directory, read
at Object.readSync (node:fs:728:3)
at tryReadSync (node:fs:434:20)
at Object.readFileSync (node:fs:480:19)
at loadData (/app/taxonium_backend/server.js:486:26) {
errno: -21,
syscall: 'read',
code: 'EISDIR'
}
```

**Comment by theosanderson** [comment]
Thanks for reporting -- please could you let me know the command you are running

**Comment by corneliusroemer** [comment]
Oh I see, this happened after:
1. Running `view_taxonium gisaidAndPublic.2022-10-05.masked.gisaidNames.taxonium.jsonl.gz --backend_port 3453`
2. Opening the URL http://localhost:8000/?backend=http://localhost:3453 in Safari

I think the issue is that the tree wasn't loaded in the backend yet.

After waiting a bit more, I then saw notifications that the tree was loading...

<img width="601" alt="image" src="https://user-images.githubusercontent.com/25161793/195106008-186d2a98-fc59-4c24-8a2f-ba3033aee31f.png">

**Comment by theosanderson** [comment]
There shouldn't be a connection between opening the browser. The process should be (this is for advice, I agree the UX could be much better):

run `view_taxonium gisaidAndPublic.2022-10-05.masked.gisaidNames.taxonium.jsonl.gz --backend_port 3453`

The backend should spontaneously start loading, wait for it to reach 100%.

Then open http://localhost:8000/?backend=http://localhost:3453 in browser.

**Comment by corneliusroemer** [comment]
I noticed a slowdown in loading nodes, probably because I was running out of memory. How much RAM you recommend to give docker for Angie's tree? I was using 7 GB by default for Docker out of my 32GB.

**Comment by corneliusroemer** [comment]
It works now, pretty cool and seemless! I'll let you know how performance is etc! So far I'm still on only 7GB will up on next load! Great work :) 

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/25161793/195108049-e159fe1b-46ee-431d-b731-fa3fce282d30.png">

**Comment by theosanderson** [comment]
Sorry not quite sure on the memory. You probably also want to set the `--memory` argument to a similar value. By default that is set to 80% of the available memory, but that available memory is determined from the calling script not from docker, so is probably set to 25 GB which sounds like it might not play well with a real 7 GB limit..

**Comment by corneliusroemer** [comment]
Alright, now I got an error that crashed everything. Axios error in browser, and this in perpetuity, too much logging 😬 

Will restart with more memory and correctly matched.

Could you somehow reduce the logging overload, it's completely flooding my terminal.

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/25161793/195111370-a859496e-a05f-451b-ae8a-9f93520d766d.png">

**Comment by theosanderson** [comment]
Identified a very long logging statement that shouldn't have been there: https://github.com/theosanderson/taxonium/commit/f3300defcd88a70ee4f59027965c5635cb4feb36

(In general it will still do quite a bit of logging - which i mostly find helpful, but agree re the stuff I cut)

There's no error message in your snippet, suggesting the backend didn't crash. It sounds like something got stuck in a loop such that the backend wasn't able to serve another request, creating the Axios error.

**Comment by theosanderson** [comment]
I managed to get stuck in that apparent infinite loop thing just now. I think express must be queuing up hundreds of requests in certain race conditions in a way it wouldn't do when running against an external server.

**Comment by corneliusroemer** [comment]
Maybe re logging, you could allow different levels - I'd prefer quieter operations by default. Especially if more people other than you will use taxoniumtools having a quieter mode could be good ;)

**Comment by theosanderson** [comment]
👍 it's about stages. it's at an early stage so having the logs to let me figure out where your thing has actually crashed is useful for now

**Comment by theosanderson** [comment]
btw I'm relatively confident the error message at the top happens when you specify a file that doesn't exist and so docker creates a new directory and mounts it (a check that the file exists in the py caller would be good)

**Comment by theosanderson** [comment]
Closing view_taxonium issues as this will be deprecated, and ultimately removed, in favour of an Electron app. Thanks for raising issues, which helped to clarify that the electron app was the best way forward.
