### ISSUE TITLE
ENH: Publish ARM64 images for taxonium frontend and backend

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#407]
I use an M1 mac so it would be amazing if there were also ARM64 images of frontend and backend - maybe this is easy, probably not. But just in case it's easy...

I'm trying but struggling to get taxoniumtools to work, not successful unfortunately so far.

**Comment by theosanderson** [comment]
Closing view_taxonium issues as this will be deprecated, and ultimately removed, in favour of an Electron app. Thanks for raising issues, which helped to clarify that the electron app was the best way forward. The electron app includes arm64 binaries.
