### ISSUE TITLE
taxoniumtools: search is very slow, maybe create index or hashmap for speedup?

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#410]
I wanted to do what @AngieHinrichs recommended and quickly get around the tree using sequence names. Unfortunately, the search took quite long, just finding a single node name took 24 seconds. That seems to be how long it takes to iterate over the entire jsonl file if there's no precreated index?

**Comment by theosanderson** [comment]
Angie said searches were slow too so I should try to figure this out!

So in terms of iterating over "the file" -- it's not a matter of reading from disk -- everything is in RAM. But yes, a search does need to iterate over each node to check if its name matches (as you say, it could maybe be implemented differently, but this is how things work atm and allows e.g. substring matches).

This backend is exactly what runs on Cov2Tree, and there searching for a single sequence takes a second or two, so I'm not clear what would be different but will try to figure it out. I guess it might just be the size of the tree.

**Comment by corneliusroemer** [comment]
Docker on Mac (especially ARM) is much slower, it could be up to a factor of 10.

For substring matching, you could still create an index of some sort that allows substring matching - which is a neat feature!

**Comment by theosanderson** [comment]
Electron could help with a lot of this if it is about Docker

**Comment by corneliusroemer** [comment]
I’m pretty certain it is at least in part due to the performance issues of docker on macOS and M1 in particular - would be good to see how long it takes for Angie, who may be running docker on linux where performance should be near native.

One other improvement would be to also publish ARM64 docker builds - if it is easy (as I mentioned in another issue I think)

**Comment by AngieHinrichs** [comment]
I'm running docker on a 2019 Mac Pro (2.6 GHz 6-Core Intel Core i7, 32GB RAM, GPU: AMD Radeon Pro 5500M 4 GB).

**Comment by theosanderson** [comment]
Right folks. New approach. https://github.com/theosanderson/taxonium/releases/tag/tax_electron contains binaries in both x64 and Arm64 for versions for an Electron desktop app. Hopefully it's relatively self-explanatory, but it's very early days. It needs port 8000 to be available at the moment, and it needs internet access as it loads taxonium.org for the client.

**Comment by theosanderson** [comment]
Closing this given the electron app. Atm I don't have plans to change the need to filter over all nodes, but it's worth keeping these ideas in mind as trees get ever bigger.

**Comment by theosanderson** [comment]
(btw I found a big bug that meant that I think things were still in practice limited to 2 GB, fixed in latest release)
