### ISSUE TITLE
Taxonium ARM64 is damaged (error by macOS)

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#412]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/25161793/195355128-e8700256-350d-476c-bffc-516660eedf93.png">

Tested on M1

**Comment by theosanderson** [comment]
Grrr. Annoyingly I don't have an M1 to test. I saw something about this at some point will research. Thanks for reporting. Why can nothing be simple :)

**Comment by theosanderson** [comment]
As I understand it the x64 version should work but slower? Would be useful to hear if that works at all for you

**Comment by corneliusroemer** [comment]
The x86 should work.

Shall I fund you an M1 mini for just $600 ;)

**Comment by theosanderson** [comment]
Related issue https://github.com/electron-userland/electron-builder/issues/5850

**Comment by theosanderson** [comment]
If you have time please could you try running `sudo xattr -r -d com.apple.quarantine "/Applications/Taxonium.app"` (or whatever the path needed is) for the ARM64 version and seeing whether that fixes it?

**Comment by theosanderson** [comment]
It sounds like I have to pay $99 per year to Apple to avoid this :(

**Comment by corneliusroemer** [comment]
Hmm, I think this is different. I had to click some stuff in security & privacy which is what you can avoid by paying $99

But the ARM problem is different. I've never seen this "broken" message ever before for any app.

**Comment by theosanderson** [comment]
OK but people in that Issue are describing a link between that and this. But does seem murky. Will try a Universal build.

**Comment by corneliusroemer** [comment]
It works! The quarantine thing seems to have helped.

I had to accept this at some point:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/25161793/195361145-7c6b860c-7de9-4dc3-b312-ddc0a6bc260c.png">

Now it's all good 🎉

**Comment by theosanderson** [comment]
🎉 don't really want to have to ask users to run that terminal command - but it's helpful to understand that the issue does relate to signing in some way. It sounds like a Universal build (that just puts x64 and Arm64 side by side) should help - for unknown reasons

**Comment by corneliusroemer** [comment]
Interesting, well it may work with the ARM build using sudo xattr -r -d com.apple.quarantine "/Applications/Taxonium.app”

It seems to at least right now.

Universal binary is easy to make, then it’ll just pick whatever works. Disadvantage is twice the binary size but that shouldn’t matter much

**Comment by theosanderson** [comment]
Universal added to https://github.com/theosanderson/taxonium/releases/tag/tax_electron . If you have time to check whether it's broken, would appreciate it.

**Comment by theosanderson** [comment]
But I'm getting some axios errors with it so still further work to do

**Comment by theosanderson** [comment]
Hoping the signing issue is solved by the universal binary.

**Comment by corneliusroemer** [comment]
Works great! Still need to unquarantine (thanks for that CLI command, much faster than via system preferences) of course but no longer broken!

**Comment by corneliusroemer** [comment]
This is amazing :) Starting to really dig Taxonium now that it doesn't crash and load fast.

It's at a point where it's getting useful - but there's of course still a lot of potential!
