### ISSUE TITLE
Taxonium Electron: Axios error, then it flashes white screen

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#413]
Managed to get backend to load, but then it shows Axios error, if I click ok screen gets white

Where can I see the logs?

<img width="791" alt="image" src="https://user-images.githubusercontent.com/25161793/195357045-722f9201-2360-4cb7-8932-03d9397b0848.png">

<img width="779" alt="image" src="https://user-images.githubusercontent.com/25161793/195357054-dc6c71db-76ab-48ce-8fec-4b649c0e9664.png">

<img width="782" alt="image" src="https://user-images.githubusercontent.com/25161793/195357065-4773635e-b8ee-4d0a-bfd8-9a9fcf3d2d95.png">

**Comment by corneliusroemer** [comment]
Is it possible to use just the electron backend with a normal browser?

**Comment by corneliusroemer** [comment]
Before clicking axios ok
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/25161793/195358714-8e525d81-e7b5-4692-bc1c-0c706264dc4a.png">

After

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/25161793/195358726-6cf79bc0-7c70-48b5-8142-b099cf9c29c5.png">

**Comment by theosanderson** [comment]
Yes, https://taxonium.org/backend=http://localhost:8000. You might need to https://superuser.com/questions/772762/how-can-i-disable-security-checks-for-localhost

**Comment by corneliusroemer** [comment]
Some cors thing?

Electron dev tools:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/25161793/195358939-c47ec4ac-aee1-449e-9814-5d67bda7a866.png">

**Comment by theosanderson** [comment]
Hmm, maybe. This should all be packaged such that we all experience the same thing though, but we're not :(

**Comment by corneliusroemer** [comment]
Issue might be that I was still running Docker in the background with taxonium on port 8000 :D

**Comment by theosanderson** [comment]
Ahhh

**Comment by theosanderson** [comment]
And yeah there is a long way to go re: checking for that sort of stuff

**Comment by theosanderson** [comment]
The port has been changed to be more unique
