### ISSUE TITLE
Taxonium Electron: Load clade in Nextstrain fails

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#415]
<img width="926" alt="image" src="https://user-images.githubusercontent.com/25161793/195362501-cd50c4d9-bea4-4046-a3e8-c460de6b3338.png">

**Comment by theosanderson** [comment]
It's expected behaviour that this is impossible -- there's no way to make it work -- but yes the button shouldn't show up. It shows up because until now backends were always expected to be accessible by the Nextstrain server.

**Comment by theosanderson** [comment]
I believe this button has been removed
