### ISSUE TITLE
DOC: Mention how to unquarantine taxonium for mac in docs

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#422]
I think it'd be useful for many people to know that they need to unquarantine Taxonium on mac.

The following command is so amazingly useful for this, thanks for showing me this (I had hitherto thought it only works manually):
```
sudo xattr -r -d com.apple.quarantine "/Applications/Taxonium.app"
```

**Comment by theosanderson** [comment]
Done, thanks https://github.com/theosanderson/taxonium/commit/b5c7c9ecdff15375a3c7a8e852bc899cb7cffa47
