### ISSUE TITLE
BUG: Tooltips do not disappear when mouse is over them -> downgraded usability

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#433]
Thanks for adding tooltips, unfortunately they stay when the cursor is on them rather than the box that triggered.

This degrades usability. See gif:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/25161793/196036314-ef22c646-bbfc-4e64-9480-57a9284d29e6.png">

![2022-10-16 14 50 03](https://user-images.githubusercontent.com/25161793/196036360-4480f166-2b74-4dc7-801b-b347b5989a07.gif)

**Comment by theosanderson** [comment]
We did always have tooltips (https://github.com/theosanderson/taxonium/issues/370#issuecomment-1243539140) I have now reverted to that style if you preferred the initial ver. That styled tooltips remain on mouseover is intended behaviour as it is needed to allow clicking on the Treenome browser one.

**Comment by corneliusroemer** [comment]
Strange, ok. The problem is that the tooltips should disappear when the mouse moves away from the area that originally triggered. But maybe this tooltips don't support that :/

They are definitely nice and visible, but not disappearing feels problematic.
