### ISSUE TITLE
BUG(electron): Loading via `https://taxonium.org/?backend=http://localhost:14860 in your browser` does not work

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#440]
I tried to access Taxonium via independent browser as opposed to Electron integrated browser but this didn't work, I got Axios Error.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/25161793/197399781-0939f579-96a5-48fc-8e36-39885bb08553.png">

> You may also be able to load https://taxonium.org/?backend=http://localhost:14860 in your browser

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/25161793/197399800-c076f1ea-52bd-46ec-ae2a-96d11c3e73a3.png">

**Comment by theosanderson** [comment]
Have you disabled CORS checks (https://github.com/theosanderson/taxonium/issues/413#issuecomment-1276195699)?

**Comment by corneliusroemer** [comment]
Hmm, it didn't show any error and I missed that comment, I've just enabled that flag `chrome://flags/#allow-insecure-localhost` and will see, thanks for the tip.

**Comment by corneliusroemer** [comment]
Alright, that seems to have worked! Would be good to add that to the little text and maybe also make the link open in an external browser - copying it is quite tricky due to small text size.

**Comment by theosanderson** [comment]
The way it is currently (phrased as "may" with small non-salient text) is an intentional gapstop choice to make it possible for super-users to do this with customized flags. In future this will be fixed more properly with a localhost server that serves the front-end too on a non-HTTPS connection.
