### ISSUE TITLE
Electron app dies with "JavaScript heap out of memory"

### ISSUE THREAD

**Issue by AngieHinrichs** [theosanderson/taxonium#456]
I'm using the latest release Electron app, and with a full tree .jsonl.gz file that I can't share publicly (will send off-github), and the app loads the tree into the backend OK.  But then when I try to view the tree (using the "You can access it [here]" link or my web browser), I get the "AxiosError: Network Error" message.  

While the green status bar says "finalising", the Taxonium Helper process using the most memory gets up to 4.10GB but then steps back to 3.91GB when the green status bar says "Loaded".  Here are the memory stats from Activity Monitor at that point:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/186983/210023818-863a85ae-fe5b-4993-9842-86e8afa19def.png">

When I click the "You can access it [here]" link, the Taxonium Helper process using more memory goes up to 4.16GB and then the process goes away and the error message appears.

Is there a way to tell the app to use more memory?  Thanks.

This might explain some other crashes I've been experiencing lately -- use a bit too much memory and bye-bye backend.  🙂 

<details>
  <summary>Click to expand end of output from app</summary>

```
stdout: Adding parents took 720ms.
Went from 49341 to 164190 nodes.
Saved cached starting vals

stdout: Starting to listen

stdout: Non SSL on port 17541
status { status: 'loaded' }

message: [object Object]
{ status: 'loaded' }
stdout: /search

stdout: {
  key: 'aa1',
  type: 'name',
  method: 'text_match',
  text: '',
  gene: 'S',
  position: 484,
  new_residue: 'any',
  min_tips: 0
}

stdout: retrieving  499a3479
not found

stdout: {
  key: 'aa1',
  type: 'name',
  method: 'text_match',
  text: '',
  gene: 'S',
  position: 484,
  new_residue: 'any',
  min_tips: 0
}

stdout: caching  499a3479

stdout: Found 0 results in 2ms
Result type was complete

stdout: Using cached values
Ready to send after 0ms.

stderr: 
<--- Last few GCs --->

[94322:0x7fc4e8008000]   300135 ms: Mark-sweep (reduce) 3814.1 (4009.4) -> 3708.2 (3892.1) MB, 2686.3 / 0.0 ms  (+ 23.2 ms in 155 steps since start of marking, biggest step 1.1 ms, walltime since start of marking 2858 ms) (average mu = 0.963, current mu =[94322:0x7fc4e8008000]   304545 ms: Mark-sweep (reduce) 3708.2 (3892.1) -> 3708.2 (3887.6) MB, 4409.8 / 0.0 ms  (average mu = 0.908, current mu = 0.000) last resort; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x110719d75 node::FatalException(v8::Isolate*, v8::TryCatch const&) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

stderr:  2: 0x110719e91 node::OnFatalError(char const*, char const*) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x10aebc180 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x10aebc094 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x10b077038 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x10b051f64 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x109db9ced v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

stderr:  8: 0x10b431f9f v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x10aedb0d1 v8::String::Utf8Length(v8::Isolate*) const [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x1106f7a9d node::Buffer::New(v8::Isolate*, char*, unsigned long) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x10af27f72 v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) [/Applications/Taxonium.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x12b9ff0fe78 
13: 0x12b9fe8ba69 
14: 0x12b9fe8ba69 
15: 0x12b9fe8ba69 
16: 0x12b9fe8ba69 
```
</details>

**Comment by theosanderson** [comment]
Thanks Angie! Huh, interesting. The intent is that it should use 3/4 of total available memory: https://github.com/theosanderson/taxonium/blob/master/taxonium_electron/src/main.js#L4 Now to figure out why it's instead sticking to 4 GB

**Comment by theosanderson** [comment]
I think this must be related to https://www.electronjs.org/blog/v8-memory-cage#:~:text=This%20means%20that%20native%20modules,a%20maximum%20size%20of%204GB.

**Comment by theosanderson** [comment]
(I'm working on trying to package node binaries with the app to address this)

**Comment by theosanderson** [comment]
Thanks so much for raising this. I suspect these issues are also what underlie a bunch of @corneliusroemer's bad experiences with crashes. This de facto 4 GB limit for Electron wasn't very well documented. It looks like this issue is fixed in [v2.0.90](https://github.com/theosanderson/taxonium/releases/tag/v2.0.90), although the performance feels a bit worse, which would be expected. 

For technical reasons the new version has separate arm64 and x64 builds, and this makes the use of the terminal to unquarantine with `sudo xattr -r -d com.apple.quarantine "/Applications/Taxonium.app"` totally essential


Let me know how you get on :)

**Comment by AngieHinrichs** [comment]
It's working great now, thanks so much Theo!

[FWIW I was still able to get around the quarantine without the terminal: open Finder, go to Applications, right-click on Taxonium, click Open, and click Open (instead of 'Move to Trash' or 'Cancel').  This time I had to try that twice -- IIRC the 'Open' option didn't appear on the final dialog the first time but maybe it was operator error -- but it definitely worked the second time.]

**Comment by theosanderson** [comment]
Ah thanks – I couldn't get that to work on my M1 Mac this time round (I used to be able with the Universal binaries) but I'll try again as that's easier for users!
