### ISSUE TITLE
Genotype legend colours don't match node colours

### ISSUE THREAD

**Issue by martinghunt** [theosanderson/taxonium#462]
Sorry if this is a duplicate of #452! Not sure, so making a new issue...

When using colour by genotype, the colours shown in the genotpye legend in the bottom left don't match the node colours in the tree. After some playing around changing the residue number, I think it might be displaying the genotype legend for the previous position that was being viewed? Not sure.

Attaching a few screenshots all of Gene S position 2. This is using the Cov2Tree of 6 million samples linked from the taxonium.org homepage. I'm also seeing the same thing in my own data (made with usher_to_taxonium).

The only difference between the screenshots is that I went to a position that wasn't 2, and then went back to position 2 and took the screenshot. The genotype key colours are different in all of them, but tree is the same.

<img width="939" alt="Screenshot 2023-01-17 at 11 25 52" src="https://user-images.githubusercontent.com/4937411/212887573-e2bfb06c-f4b1-4d2e-8695-6ebc3c213c32.png">
<img width="936" alt="Screenshot 2023-01-17 at 11 25 29" src="https://user-images.githubusercontent.com/4937411/212887580-242faa29-8773-4154-9f66-9795146cd60b.png">

<img width="938" alt="Screenshot 2023-01-17 at 11 25 41" src="https://user-images.githubusercontent.com/4937411/212887578-2eba3636-4d48-4ba5-8830-7e90aca0fbc9.png">

<img width="939" alt="Screenshot 2023-01-17 at 11 26 21" src="https://user-images.githubusercontent.com/4937411/212887560-1ed39c92-14d1-462e-a863-542a2ad41d7f.png">

**Comment by theosanderson** [comment]
Huh, thanks for reporting! No that's not a known issue!

**Comment by theosanderson** [comment]
(Notes to self:)
This is not related to the React.memo of the key component, nor to the dependency array in useLayers. It might be to do with the genotype cache.

**Comment by theosanderson** [comment]
Hopefully fixed -- thanks for reporting!

**Comment by martinghunt** [comment]
oh wow that was fast! Thanks, looks good now!
