### ISSUE TITLE
Versioning the electron app

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#474]
I was trying to see whether I needed to update but realized the electron app wasn't versioned - it says 0.0.0 in "about"

So do the release assets. Would be nice if the build version was contained in the electron app and release asset name as well.

I faintly remember having raised this before but couldn't find the issue.

**Comment by theosanderson** [comment]
Thanks, yeah this is a known low priority issue. If anyone wants to figure it out they are welcome to. That said, given that we use a monorepo atm it might not help you a ton (i.e. false "new" versions).

**Comment by theosanderson** [comment]
Complete
