### ISSUE TITLE
Coloring by nt shows non-N bases, but amino acid is showing X where unmutated

### ISSUE THREAD

**Issue by AngieHinrichs** [theosanderson/taxonium#523]
Hi Theo!  Viewing a tree from @iqbal-lab, when I choose Color by: Genotype and it defaults to S:484, the unmutated parts of the tree are all grey and mouseover shows 'X' for the grey sequences:
<img width="1088" alt="image" src="https://github.com/theosanderson/taxonium/assets/186983/5f2e0a0a-479c-44c9-9b22-3ac5c3c21810">
It's even more striking for a position like 377 - almost the entire tree is grey.  But if I color by nucleotide at the same positions (22691-22693, thanks for codon2nucleotide 😃) then all nucleotide bases are colored correctly from the root of the tree.

**Comment by theosanderson** [comment]
Hey so unfortunately when I overhauled GenBank import in taxoniumtools a few months back to deal with compound features I broke the annotation of the root node without noticing. This was recently fixed https://github.com/theosanderson/taxonium/tree/v2.0.111 but probably too late for this tree. Really sorry for the inconvenience. Please let me know if it persists in any new trees.

**Comment by AngieHinrichs** [comment]
Ah, thanks Theo, so this should just go away when they update taxoniumtools and re-run.  I'll close this now and reopen if that doesn't do the trick.

**Comment by martinghunt** [comment]
Thanks Theo, can confirm that the tree was made using taxoniumtools 2.0.110. If I rerun with 2.0.111 then it's mostly fixed.

But I am getting a glitchy display issue where depending on zoom level everything turns grey. Maybe related? I don't know. I've not seen this happen before.

Two screenshots attached of the same session, only difference between them is I used the mouse wheel to zoom in/out. Running on taxonium.org/M1 mac/safari.

<img width="1900" alt="taxonium 1" src="https://github.com/theosanderson/taxonium/assets/4937411/50647092-4419-4c9a-aa27-1277429f8eb5">

<img width="1898" alt="taxonium 2" src="https://github.com/theosanderson/taxonium/assets/4937411/8bfc8a6c-afbb-4ff4-8bd7-9523495fc37f">

**Comment by theosanderson** [comment]
@martinghunt - huh! that's a new one to me.

Some questions:
1. Can you get this to happen at cov2tree.org?
2. I've made some changes to some bits of (web) Taxonium lately to add new colour customisability. https://cov2tree-9k82lpuou-theosanderson.vercel.app/ is a version before those changes - does that have the same bug? If not it might be a temporary fallback for you
3. Is this generally very reproducible, i.e. does it happen every time?

If it doesn't happen on cov2tree.org please could you send a file where it happens over to theo@theo.io - dropboxed or whatever?

**Comment by theosanderson** [comment]
OK I can reproduce this - doesn't happen with web taxonium but does with a JSONL

**Comment by theosanderson** [comment]
It indeed appears that https://cov2tree-9k82lpuou-theosanderson.vercel.app/ is unaffected if that helps in the short term

**Comment by theosanderson** [comment]
Just using this ticket for notes to myself for a bit:
- easiest way to reproduce is zoom right in when not on "genotype" mode, then switch to genotype mode. works for cov2tree too.
- relates to the colorCache in useColorBy - if you disable caching it stops happening
- presumably there is an initial point where it can't find parents and so cache gets set to "X". that initial point where it can't find parents shouldn't happen.

**Comment by theosanderson** [comment]
This PR, is the issue. 

https://github.com/theosanderson/taxonium/pull/519

We can walk through it to see when the issue appeared. 2204d84 bad e8bbbc4 good

**Comment by theosanderson** [comment]
Hopefully a fix is rolling out, preview at https://cov2tree-git-fix-genotype-theosanderson.vercel.app/ . If it doesn't fix the issue please let me know. Thanks for reporting

**Comment by martinghunt** [comment]
Thanks for fixing so fast! That preview is working perfectly for me

**Comment by theosanderson** [comment]
Awesome - (should be same on main site)
