### ISSUE TITLE
Left/right scroll for long branches

### ISSUE THREAD

**Issue by yatisht** [theosanderson/taxonium#54]
As you would notice, some branches in the latest trees are quite long and cut across the right margin. To make them viewable, it would be nice to add a left/right scroll in the interface. Thanks.

**Comment by theosanderson** [comment]
Thanks Yatish. I have some progress on this in some branch, with a toggle between horizontal and vertical movement. But I also wonder whether the ability to select a subtree to zoom in on could achieve the same thing which is what I'd moved onto. One or other definitely seems important!

**Comment by theosanderson** [comment]
A stupid temporary hack is to control-minus yourself a "bigger screen"

**Comment by yatisht** [comment]
The control-minus hack did work and is good enough for now!

I am not sure how you plan to implement the subtree zoom, but won't it suffer from the same long branch issues?

**Comment by theosanderson** [comment]
Yeah one would need to rescale everything to fit on the screen! Unclear if that's the best way forward let's see

**Comment by theosanderson** [comment]
Exists in V2 - still need horizontal zoom
