### ISSUE TITLE
Pop up displays are no longer coming to the front on Taxonium

### ISSUE THREAD

**Issue by ucscbrianlee** [theosanderson/taxonium#555]
Example image: 
<img width="263" alt="BlockedPopUp" src="https://github.com/theosanderson/taxonium/assets/104174066/af3ffc59-ec3e-4e2f-8a7b-d35a7059bbce">

Note that ORF3a pop-up shows only "F3a:Q57H"  because the OR is behind the Treenome display and thus blocked.  This didn't happen in the past.

Here is a quick [example link to try it out](https://taxonium.org/?backend=https%3A%2F%2Fapi.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22meta_genbank_accession%22%2C%22method%22%3A%22text_per_line%22%2C%22text%22%3A%22OQ381704.1%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%5D&treenomeEnabled=true).

1. Click link
2. Hover mouse over any vertical bar element (variants)
3. Notice no pop-up information
4. Move mouse towards the furthest right of the screen (near Search box and Color by options)
5.  Spot that pop-ups are happening, just behind the main Treenome browser image. 

These pop ups identify the variant names and thus are pretty integral to the functionality of the powerful and very cool Treenome Browser tool.

All the best,
Brian Lee

**Comment by theosanderson** [comment]
Thank you for reporting this and for the helpful repro example!

**Comment by ucscbrianlee** [comment]
My pleasure, thank you for the fix and the awesome powerful tool!
