### ISSUE TITLE
Parsing NS file 

### ISSUE THREAD

**Issue by Sanyukta2001** [theosanderson/taxonium#572]
so i used UShER commands to make a .pb MAT file. I converted that to Json file using this command :
usher_to_taxonium --input global_assignments.pb --output gb.json

Then I uploaded the resulted json file to Taxonium browser, but it's the screen is  showing 'Parsing NS file' and has been buffering for more than an hour now and i still see no tree made. What's wrong?

**Comment by theosanderson** [comment]
Hi @Sanyukta2001,

`usher_to_taxonium` actually outputs technically not `json` but `jsonl` or `ndjson` (https://jsonlines.org/).

I recommend using the `.jsonl` extension. If you use that, Taxonium will automatically detect that you are uploading a Taxonium format file. If you upgrade a `.json` then by default Taxonium assumes this is a JSON file as outputted by Nextstrain tools, which means it will parse the file incorrectly.

Alternatively, if you didn't want to rename your file you would need to choose "Taxonium JSONL" in the dropdown:
<img width="494" alt="image" src="https://github.com/theosanderson/taxonium/assets/19732295/31eb308f-a1e8-4f3d-97a5-4aa1bd2eb93e">

Hope this helps, let us know if you still have problems.
