### ISSUE TITLE
MatUtils CLI to identify mutation spread in large populations

### ISSUE THREAD

**Issue by Sanyukta2001** [theosanderson/taxonium#575]
After making MAT tree file with usher, I am confused on whether to use matUtils extract or summary  to find mutations that have occurred or spread frequently/ within large group of population

Maybe I am getting it wrong but is it possible? Or do we have to manually look:dig in through our visualization in Treenome to look for mutations spread in large populations?

**Comment by theosanderson** [comment]
Sorry you'd have to ask the UShER team about matUtils.

With Taxonium it isn't very possible at the moment to search for mutations that have spread frequently, but if you have a mutation and want to know how many times it has been seen on the tree, possibly with a minimum number of descendants for each node, you can use mutation search.

**Comment by AngieHinrichs** [comment]
> find mutations that have occurred or spread frequently/ within large group of population 

I don't know of a way to do this directly in matUtils, but a tool called pyR0 has been published to do just that:

https://www.science.org/doi/10.1126/science.abm1208
https://github.com/broadinstitute/pyro-cov/

**Comment by Sanyukta2001** [comment]
@AngieHinrichs thank you for letting me know about Pyrocov, but I fail to understand what kind of input should be given to identify mutation spread, more specifically to plot it. 
It says to load .pt file but how do I make this? I couldn't find any docs for this. 
What data needs to be loaded for this? If you know this please let me know. I have asked to Pyrocov as well but got no replies,

**Comment by AngieHinrichs** [comment]
Hi @Sanyukta2001, I have not run pyrocov so I don't know what the .pt file is, sorry.
