### ISSUE TITLE
Extracting mutation data from the jsonl tree

### ISSUE THREAD

**Issue by Biophylo2001** [theosanderson/taxonium#581]
Hi, I've generated my SARS-CoV-2 tree (jsonl format) using the usher command lines. Now, I want to extract mutation frequency and identify predominant amino acid mutations in my tree. How can I efficiently do this so that i can use that information with Taxonium's> Search > Mutation section for studying spread since manually inputting all mutations is time-consuming.

Do I do that with  from my  combined VCF files or can it be done using the JSONL file itself? How was this process implemented in creating the Cov2tree? Thank you. Here's how my merged VCF file looks:

[snpeffdata.vcf.gz](https://github.com/theosanderson/taxonium/files/14936627/snpeffdata.vcf.gz)

Thanks a lot

**Comment by theosanderson** [comment]
The first line of the jsonl contains various bits of data for the whole tree, including a list of mutations. Each line below has a list of mutations with numbers where the number is the index of the mutation in the initial list. So you could analyse it with that. You can also analyse the Usher protobuf with e.g. BTE (big tree explorer)

**Comment by Biophylo2001** [comment]
Thank you for your reply, I have tried using the jsonl file to extract the mutation data however, in the Treenome browser it doesn't show the accurate number of result. Maybe I am doing something wrong. 

For example, For the S 1082 mutation in the screenshot, it shows only "1 result" circled at the root node. What does that mean? I am sure there are plenty of S 1082 residue mutations present but its not shown accurately. 

![Screenshot (375)](https://github.com/theosanderson/taxonium/assets/137520035/436b82db-3c08-4ac7-990e-3aa60ce54bb4)

**Comment by theosanderson** [comment]
Sorry that I missed this. Without seeing your tree file it's hard to assess what's going on here.

**Comment by Biophylo2001** [comment]
@theosanderson Here i have attached my tree file . Thank you for looking into it. 
[treefile.jsonl.gz](https://github.com/theosanderson/taxonium/files/15088441/treefile.jsonl.gz)

**Comment by theosanderson** [comment]
S:1082 appears to be C throughout your tree 
<img width="1447" alt="image" src="https://github.com/theosanderson/taxonium/assets/19732295/61fac5a1-6650-43bb-932e-cc4da8e0c1ba">
