### ISSUE TITLE
How to set ladderizeTree in Taxonium React Component

### ISSUE THREAD

**Issue by UTNK** [theosanderson/taxonium#583]
Hi, I deeply appreciate your great work.
I'm trying to use the Taxonium React Component (https://docs.taxonium.org/en/latest/component.html) in my web application, but I cannot ladderize the tree I would like to visualize.
Could you tell me how to set the ladderizeTree option in the Taxonium React Component?

**Comment by theosanderson** [comment]
I'm travelling at the moment so can't test this, but looking at the code, you should be able to add `ladderize : true` to the sourceData in those examples. Could you try that and let me know if you still have issues.

**Comment by UTNK** [comment]
It works! Thank you for your reply.
