### ISSUE TITLE
how to transform taxonium to auspice?

### ISSUE THREAD

**Issue by liamxg** [theosanderson/taxonium#591]
Dear @theosanderson,

how to transform taxonium to auspice, thanks.

**Comment by theosanderson** [comment]
You can click on nodes with smaller numbers of descendants and click these buttons:
<img width="429" alt="image" src="https://github.com/theosanderson/taxonium/assets/19732295/f579a08a-f8ba-45e3-b4f5-e8bd286f69d7">
