### ISSUE TITLE
Amino acid branch mutation duplicated on Usher tree

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#597]
_I'm not sure if this is an issue with Taxonium or Usher but as I noticed it in Taxonium I thought I start here but also ping @AngieHinrichs_

I noticed a branch amino acid mutation appearing twice leading to node 2254780 on the 2024-06-06 tree with GISAID names. Example sample tipwards of the branch: SouthAfrica/CERI-KRISP-K059329_COVID477/2023|EPI_ISL_18412393|2023-09-08

<img width="1508" alt="image" src="https://github.com/theosanderson/taxonium/assets/25161793/305864e8-7ced-48a6-8c7f-31f48ff08d38">

```

Mutations at this node:
ORF1a:L3829F, ORF1ab:L3829F, ORF1b:G662S, ORF8:G8*, S:H146Q, S:L368I, S:F490S, nt:C11750T, nt:G15451A, nt:T15939C, nt:T17859C, nt:C22000A, nt:C22664A, nt:T23031C, nt:G27915T
```

`ORF1a:L3829F` appears twice

I'm using the latest Taxonium release locally.

**Comment by theosanderson** [comment]
Are you looking at `ORF1a` and `ORF1ab`?
