### ISSUE TITLE
Add lineage annotations on internal branches

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/taxonium#598]
It would be nice if branches were able to display Pango lineage as well, not just tips

This is what a branch tooltip shows:
<img width="293" alt="image" src="https://github.com/theosanderson/taxonium/assets/25161793/3f8b4c99-fdfb-4626-8880-fbd1def42b0d">

Vs a tip tooltip:
<img width="625" alt="image" src="https://github.com/theosanderson/taxonium/assets/25161793/4b8d566e-9158-45b0-a8e8-0732bb48013b">

Maybe this is possible and the Usher export just lacks the annotation - or maybe it's not supported by Taxonium in any case.

**Comment by theosanderson** [comment]
This is technically already supported by Taxonium, and in the case of lineages is something that would probably want to come from UShER. There is an ongoing hope to allow the inference of ancestral states by Fitch parsimony, which would help (but not so needed for lineages)

**Comment by AngieHinrichs** [comment]
@corneliusroemer what method of UShER export are you using?  matUtils extract?
