### ISSUE TITLE
usher_to_taxonium --chronumental: add date output as metadata-like value?

### ISSUE THREAD

**Issue by AngieHinrichs** [theosanderson/taxonium#607]
Hi Theo -- I ran chronumental in usher_to_taxonium and it worked great, produced a nice [time-tree](https://taxonium.org/?protoUrl=https%3A%2F%2Fhgwdev.gi.ucsc.edu%2F~angie%2Fh5n1_outbreak_2024.2024-09-23.chronumental.jsonl.gz&xType=x_time&color=%7B%22field%22%3A%22meta_mutdiffsel%22%7D&mutationTypesEnabled=%7B%22aa%22%3Atrue%2C%22nt%22%3Atrue%7D) and date output file.  

It would be even awesomer if I could hover/click on a node and see the chronumental-inferred date as if it were a metadata column, instead of having to grep in the date output file when I'm curious what date was inferred for a sample with missing date.

If there's not already a better way, perhaps a new usher_to_taxonium option like `--chronumental_add_inferred_date <column_name>` or something like that could be added?  If you don't have time, I think I see where that could be implemented in taxoniumtools/usher_to_taxonium.py and taxoniumtools/utils.py, and I could take a stab at it and send a PR if you'd like.  I'm thinking that a new "column" could be added to the `metadata_dict` for each node and `metadata_cols` list, so that when it's time to dump JSONL, `get_node_object` would see it as just another metadata column to dump out.

(It looks like even if `--chronumental_date_output` is not given, a date output file is still produced, with the name `chronumental_dates_`_metadataFile_`.tsv`.)

**Comment by theosanderson** [comment]
Hey @AngieHinrichs ,

Thanks a lot for flagging this. Your proposed solution sounds great! If you do find yourself with the bandwidth to make the PR I would certainly accept it. (If not I would hope to get to this, but likely not entirely immediately).

**Comment by theosanderson** [comment]
Thank you to Angie for completing this in https://github.com/theosanderson/taxonium/pull/608
