### ISSUE TITLE
legend for colorRamps

### ISSUE THREAD

**Issue by AngieHinrichs** [theosanderson/taxonium#610]
I got some user feedback about the legend for colorRamps having unsorted discrete values -- I know you're already aware, but I'm adding an issue just to keep it top-of-mind.  🙂  Thanks!

**Comment by theosanderson** [comment]
Thanks for the motivation Angie - implemented in #611

**Comment by theosanderson** [comment]
(as always, do let me know of problems!)

**Comment by theosanderson** [comment]
Oops - I broke the non-ramp case - fixing

**Comment by AngieHinrichs** [comment]
Amazing!  Thanks Theo!
