### ISSUE TITLE
Extract multiple sequence alignment from Treenome from .jsonl

### ISSUE THREAD

**Issue by Zheludev** [theosanderson/taxonium#628]
Hi Taxonium,

This is a great tool!

I have a .jsonl of a large CoV-2 Taxonium tree (Hunt et al., 2024) and I would love to extract the "treenome" alignment as conventional aa and nt multiple sequence alignments. Is there a way to do this, or ways to achieve similar results?

Thank you in advance for any help!

IZ

**Comment by theosanderson** [comment]
Hi,

There isn't a specific way to do that I'm afraid. Note that an MAT doesn't fully capture a sequence alignment as it doesn't know about Ns.

The viridian preprint by @martinghunt and co. seems to say

> All Viridian consensus sequences that are in the global tree, split over two tar archive files
(https://doi.org/10.6084/m9.figshare.25713225, https://doi.org/10.6084/m9
.figshare.27194637), which contain the sequences split over multiple xzipped FASTA
files. These are the same batched FASTA files used when building the trees.
