### ISSUE TITLE
Weird bit of the tree

### ISSUE THREAD

**Issue by theosanderson** [theosanderson/taxonium#76]
Hey @AngieHinrichs, for info @mg14 pointed out [this weird bit of the tree](https://cov2tree.org/?protoUrl=https%3A%2F%2Fhgwdev.gi.ucsc.edu%2F~angie%2FUShER_SARS-CoV-2%2Fpublic-latest.all.masked.taxodium.pb.gz&blinking=false&search=%5B%7B%22id%22%3A0.4972933414599987%2C%22category%22%3A%22genbanks%22%2C%22value%22%3A%22%22%2C%22enabled%22%3Atrue%2C%22aa_final%22%3A%22any%22%2C%22min_tips%22%3A1%2C%22aa_gene%22%3A%22S%22%2C%22search_for_ids%22%3A%22OK403054.1%5CnOK421142.1%22%7D%5D&colourBy=%7B%22variable%22%3A%22lineage%22%2C%22gene%22%3A%22S%22%2C%22colourLines%22%3Afalse%2C%22residue%22%3A%22681%22%7D&zoomToSearch=0) which is sort of I think a snapshot of Delta compressed into a small sister lineage. 

![image](https://user-images.githubusercontent.com/19732295/136818001-ba298984-ffe1-4487-8708-02f6204a07f5.png)

My best theory was that this is about masking and stuff but not really sure. Definitely not asking for any action on this, and there will always be oddities in the tree but I wasn't aware of this particular one so flagging in case you weren't, and if you have any particular insights feel free to share :)

**Comment by AngieHinrichs** [comment]
Thanks for pointing that out @theosanderson and @mg14.  Yes, this isn't the first time we've seen some dubious branches gaining enough Delta mutations to start attracting normal Delta sequences away from the main Delta branch.  There are enough sequences that have seemingly random subsets of Delta mutations to form those branches (and not just in the ARTIC v3 amplicon dropout region).  I'm hoping that if I exclude some sequences and re-optimize the tree, those bad attractors will go away and the "normal" sequences will be placed on the main Delta branch.  Even if that works, it's something I'll probably have to do again as more weird sequences and branches accumulate.  I'll try some things...  (and in the meantime, yes, we could be masking more positions for Delta...)

**Comment by theosanderson** [comment]
Amazing! Taxonium couldn't do without a tree!!! Thanks so much for all your hard work!!
