### ISSUE TITLE
colors or labels for branches/internal nodes?

### ISSUE THREAD

**Issue by AngieHinrichs** [theosanderson/taxonium#85]
One thing that would be extremely useful for flagging problematic parts of the tree would be the ability to color or label the lines for internal nodes -- in particular, I would like to highlight internal nodes that have back-mutations, because a concentration of those is usually a really bad sign.  I would love to be able to color a line as a 'red flag'.  Labels would be fine too unless they disappeared when zoomed out (they would hopefully be sparse, but not-sparse would be a bad sign & OK to look ugly).

If that would be a real pain, then no worries, I'll figure out some way to color leaf nodes, perhaps by the number of back-mutations on the path to the leaf node.  But it would be awesome to keep the usual leaf-coloring options while having branch line colors too.  :)

**Comment by theosanderson** [comment]
Btw I'm not 100% certain about the stuff above, especially the metadata-without-name thing. If you have any issues pls assume it's at my end, let me know, and I'll solve it

**Comment by theosanderson** [comment]
FYI new settings available for this stuff, and what I said above about how nodes are defined is no longer true -- leaves now are nodes with `num_tips==1`: 
![image](https://user-images.githubusercontent.com/19732295/168876779-91f0cf9e-2a23-413c-b58b-3f95101236f0.png)
